# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mphantom
tagline:          ''
description:      'life is short,I done something never have done before'
url:              http://mphantom.com

author:
  name:           'mphantom'
  email:          wushaorongvs@gmail.com

paginate:      10

# Custom vars
version:          0.0.3

# Comments


